# Generated by Django 4.0 on 2022-04-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=25)),
                ('naran', models.CharField(max_length=100)),
                ('tinan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SentruVotasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatin_votasaun', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('Natl', 'Nasionál'), ('Intl', 'Internasionál')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipuEleisaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipu', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kandidatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100)),
                ('observasaun', models.CharField(max_length=255)),
                ('afiliasaun_partidaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apuramentu.partidu')),
            ],
        ),
        migrations.CreateModel(
            name='Eleisaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinan', models.IntegerField()),
                ('observasaun', models.CharField(max_length=255)),
                ('total_eleitores', models.IntegerField()),
                ('tipu_eleisaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apuramentu.tipueleisaun')),
            ],
        ),
        migrations.CreateModel(
            name='Apuramentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votu', models.IntegerField()),
                ('kandidatu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kandidatu', to='apuramentu.kandidatu')),
                ('sentru_votasaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apuramentu.sentruvotasaun')),
            ],
        ),
    ]
