# Generated by Django 4.0 on 2022-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuramentu', '0003_apuramentu_eleisaun_eleisaun_ronda'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidatu',
            name='numeru_sorteiu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
